language: rust

matrix:
  include:
    - rust: stable
    - rust: 1.38.0 # minimum version supported by big_enum_set.
    - rust: beta
    - rust: nightly

script:
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/big_enum_set"
  - cargo test --features=serde
  - cargo test --release
  - cargo test --features=serde --release
