name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rustver: ["stable", "beta", "nightly", "1.38.0"]
        args: ["", "--features serde", "--release --all-features"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rustver }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.args }}
